# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0 # Use the latest version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 24.4.2 # Use the latest version
    hooks:
      - id: black
        language_version: python3.10 # Match your project's Python version
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0 # Use the latest version
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix] # Auto-fix and fail if fixes were made
      - id: ruff-format # if you want to use ruff for formatting instead of/alongside black
