# conf/model/tft_default.yaml
_target_: pytorch_forecasting.models.temporal_fusion_transformer.TemporalFusionTransformer # Will be used by GlobalTFT's from_dataset

# These are parameters for TemporalFusionTransformer.from_dataset()
# Passed via model_specific_params in train.py to GlobalTFT
hidden_size: 64        # follows plan’s grid
lstm_layers: 2
dropout: 0.10
# embedding_sizes will be calculated in train.py and passed in

# QuantileLoss configuration
loss:
  _target_: pytorch_forecasting.metrics.QuantileLoss
  quantiles: [0.05, 0.5, 0.95]

# Other TFT params can be added here as needed, e.g.:
# attention_head_size: 4
# hidden_continuous_size: 32
# output_size: 7 # for quantiles [0.05, 0.1, 0.25, 0.5, 0.75, 0.9, 0.95]
# target_idx: 0 # If single target, otherwise handled by target list in TimeSeriesDataSet
