# conf/model/tft_default.yaml
_target_: market_prediction_workbench.model.GlobalTFT

# Parameters for GlobalTFT constructor
learning_rate: 1e-3
weight_decay: 1e-5

# Hyperparameters for the underlying TemporalFusionTransformer
# These will be filtered into model_specific_params in train.py
hidden_size: 64
lstm_layers: 2
dropout: 0.10

# --- MODIFIED PART ---
# The loss is now defined in its own file.
# You can easily switch between loss functions by changing the default here
# or by overriding from the command line: model/loss=quantile
defaults:
  - loss: directional # <-- This is the key change
  - _self_

# The 'loss' dictionary will be instantiated by Hydra and passed to the model
# because of the defaults list above. We remove the old hardcoded loss.
# embedding_sizes will be calculated in train.py and added to model_specific_params
