# conf/model/tft_default.yaml

_target_: "market_prediction_workbench.model.GlobalTFT" # Path to our model class

# These are model_specific_params that GlobalTFT's __init__ expects
# Parameters for TemporalFusionTransformer.from_dataset()
hidden_size: 64
lstm_layers: 2
dropout: 0.1
attention_head_size: 4
# output_size: will be inferred from target_quantiles in data config or by TimeSeriesDataSet
# loss: will be inferred (QuantileLoss) by TFT if quantiles are set in TimeSeriesDataSet / data_config

# These are passed to GlobalTFT's __init__ directly
learning_rate: 0.001
weight_decay: 0.00001

# embedding_dims: Can be specified here if we want to override TimeSeriesDataSet auto-inference
# Will be calculated in train.py and merged into this config before model instantiation
# Example structure:
# embedding_dims:
#   ticker_id: 32 # this would be calculated (num_tickers**0.25, etc.)
#   sector_id: 10
