# conf/model/tft_default.yaml
_target_: market_prediction_workbench.model.GlobalTFT # Changed this line

# Parameters for GlobalTFT constructor
learning_rate: 1e-3 # Added
weight_decay: 1e-5  # Added

# Hyperparameters for the underlying TemporalFusionTransformer
# These will be filtered into model_specific_params in train.py
hidden_size: 64
lstm_layers: 2
dropout: 0.10
loss:
  _target_: pytorch_forecasting.metrics.QuantileLoss
  quantiles: [0.05, 0.5, 0.95]
# embedding_sizes will be calculated in train.py and added to model_specific_params
