_target_: pytorch_forecasting.metrics.MultiLoss
metrics:
  - _target_: pytorch_forecasting.metrics.QuantileLoss
    quantiles: [0.05, 0.5, 0.95]
  - _target_: market_prediction_workbench.losses.DirectionalLoss
    directional_penalty: 1.5 # Use a less aggressive penalty
weights: [0.7, 0.3] # Give 70% weight to QuantileLoss and 30% to DirectionalLoss
