# conf/trainer/default_trainer.yaml
epochs: 10
batch_size: 4096
num_workers: 8

max_epochs: ${trainer.epochs}
accelerator: "auto"
devices: "auto"

early_stopping_monitor: "val_loss"
early_stopping_patience: 5
early_stopping_mode: "min"

lr_monitor_logging_interval: "epoch"
gradient_clip_val: 1.0

# WandB
use_wandb: true
wandb_project_name: "market-tft"
wandb_entity: "rolandpolczer-roland-polczer"

# NEW
use_weighted_sampler: true
